pfj-31 improve error handling on provisioning
Instituto-Atlantico/janus pull request #19
Opened 2023-04-27 18:32 UTC by vitorestevamia

This PR started with the objetive of handling errors on the invitation exchange, but finished with a general improvement and small refactor of the provisioning function

2023-04-28 11:22 UTC, AnselmoLacerda approved these changes

2023-04-28 17:32 UTC, elazzarin approved these changes

2023-04-28 18:32 UTC, elazzarin requested changes

2023-04-28 18:32 UTC, elazzarin commented on pkg/agent_deploy/agent.go
> +	logger.InfoLogger("Executing command %s", command)
```suggestion
	logger.InfoLogger("Running the %s command", command)
```

2023-04-28 18:32 UTC, elazzarin commented on pkg/mqtt_pub/mqtt_pub.go
> +func PublishMessage(brokerIp string, credentals BrokerCredentials, sensorData map[string]any) error {
```suggestion
func PublishMessage(brokerIp string, credentials BrokerCredentials, sensorData map[string]any) error {
```

2023-04-28 18:32 UTC, elazzarin commented on pkg/mqtt_pub/mqtt_pub.go
> +	publicationTopic := fmt.Sprintf("%s/attrs", credentals.Username)
```suggestion
	publicationTopic := fmt.Sprintf("%s/attrs", credentials.Username)
```

2023-04-28 18:32 UTC, elazzarin commented on pkg/mqtt_pub/mqtt_pub.go
> +	opts.SetUsername(credentals.Username)
```suggestion
	opts.SetUsername(credentials.Username)
```

2023-04-28 18:32 UTC, elazzarin commented on pkg/mqtt_pub/mqtt_pub.go
> +	opts.SetPassword(credentals.Password)
```suggestion
	opts.SetPassword(credentials.Password)
```

2023-05-02 17:51 UTC, elazzarin approved these changes
Excellent job

2023-05-02 17:57 UTC, merged